[helpers]

[default]
depends = []

[default.files]
kitty = "~/.config/kitty"
nvim = "~/.config/nvim"
zshrc = "~/.zshrc"
"zshrc.d" = "~/.zshrc.d"

[default.variables]

[settings]
default_target_type = "automatic"
